#!/usr/bin/env node
/**
 * Orchestrator: fetch → render → hash → rewrite README.
 *
 * Runs identically on a laptop and in CI. The only input is GITHUB_TOKEN;
 * in the Action that's the built-in one, locally it's whatever you export.
 *
 * Ordering matters: this runs *after* the snake step in the workflow, so the
 * content-hash pass covers the snake SVGs too and they get cache-busted along
 * with everything else.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { fetchProfile } from './github.mjs';
import { THEMES } from './svg/tokens.mjs';
import { loadFont } from './svg/type.mjs';
import { hero } from './svg/hero.mjs';
import { marquee } from './svg/marquee.mjs';
import { card } from './svg/card.mjs';
import { stats } from './svg/stats.mjs';
import {
  hashFile,
  assetUrl,
  picture,
  replaceRegion,
  projectGrid,
  projectTable,
  contactRow,
} from './readme.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'assets/generated');

const LOGIN = process.env.PROFILE_LOGIN || 'Abhi-desig';
const BRANCH = process.env.PROFILE_BRANCH || 'main';
const REPO_PATH = process.env.GITHUB_REPOSITORY || `${LOGIN}/${LOGIN}`;

/** Filesystem-safe asset name for a repo. */
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function main() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    console.error(
      'GITHUB_TOKEN is required.\n' +
        '  In Actions it is provided automatically.\n' +
        '  Locally: export GITHUB_TOKEN=$(gh auth token)  — or any PAT with public read scope.',
    );
    process.exit(1);
  }

  const config = JSON.parse(readFileSync(join(ROOT, 'profile.config.json'), 'utf8'));
  console.log(`→ fetching github.com/${LOGIN}`);
  const data = await fetchProfile(LOGIN, token, config);
  console.log(
    `  ${data.repos.length} repos · ${data.stats.contributions} contributions · ${data.stats.commits} commits`,
  );

  const fonts = {
    bold: loadFont(join(ROOT, 'assets/fonts/SpaceGrotesk-Bold.ttf')),
    medium: loadFont(join(ROOT, 'assets/fonts/SpaceGrotesk-Medium.ttf')),
  };

  mkdirSync(OUT, { recursive: true });

  // Clear stale card SVGs so a deleted or renamed repo doesn't leave an orphan
  // asset behind. The snake files are produced by a different step — leave them.
  for (const f of readdirSync(OUT)) {
    if (f.startsWith('card-')) rmSync(join(OUT, f));
  }

  const written = [];
  const write = (file, svg) => {
    writeFileSync(join(OUT, file), svg);
    written.push(file);
  };

  for (const key of ['dark', 'light']) {
    const theme = THEMES[key];
    write(`hero-${key}.svg`, hero({ data, theme, fonts }));
    write(`marquee-${key}.svg`, marquee({ data, theme }));
    write(`stats-${key}.svg`, stats({ data, theme, fonts }));
    data.repos.forEach((repo, index) => {
      write(`card-${slug(repo.name)}-${key}.svg`, card({ repo, index, theme, fonts }));
    });
  }
  console.log(`→ wrote ${written.length} svg files`);

  // ── URLs ────────────────────────────────────────────────────────────────
  const url = (file) => {
    const path = join(OUT, file);
    if (!existsSync(path)) return null;
    return assetUrl({
      repoPath: REPO_PATH,
      branch: BRANCH,
      file: `assets/generated/${file}`,
      hash: hashFile(path),
    });
  };

  const cardUrl = (repo, theme) => url(`card-${slug(repo.name)}-${theme}.svg`);

  // ── README ──────────────────────────────────────────────────────────────
  const readmePath = join(ROOT, 'README.md');
  let readme = readFileSync(readmePath, 'utf8');

  readme = replaceRegion(
    readme,
    'HERO',
    picture({
      dark: url('hero-dark.svg'),
      light: url('hero-light.svg'),
      alt: `${data.user.name} — ${data.user.role}. ${data.user.tagline}`,
    }),
  );

  readme = replaceRegion(
    readme,
    'MARQUEE',
    picture({
      dark: url('marquee-dark.svg'),
      light: url('marquee-light.svg'),
      alt: `Stack: ${data.stats.languages.slice(0, 6).map((l) => l.name).join(', ')}`,
    }),
  );

  readme = replaceRegion(readme, 'PROJECTS', projectGrid(data.repos, cardUrl));
  readme = replaceRegion(readme, 'INDEX', projectTable(data.repos));

  // The snake is generated by the workflow step before this one. Locally it
  // won't exist, so fall back to the stats panel alone rather than emitting a
  // broken image reference into a committed README.
  const snakeDark = url('github-snake-dark.svg');
  const snakeLight = url('github-snake.svg');
  const statsBlock = picture({
    dark: url('stats-dark.svg'),
    light: url('stats-light.svg'),
    alt: `${data.stats.contributions} contributions, ${data.stats.commits} commits, ${data.stats.repoCount} public repos`,
  });
  const snakeBlock =
    snakeDark && snakeLight
      ? `\n\n${picture({
          dark: snakeDark,
          light: snakeLight,
          alt: 'Contribution graph, consumed by a snake',
        })}`
      : '';
  if (!snakeDark) console.log('  (no snake yet — generated by the workflow step)');

  readme = replaceRegion(readme, 'STATS', `${statsBlock}${snakeBlock}`);

  readme = replaceRegion(readme, 'CONTACT', contactRow(config.links, data));

  writeFileSync(readmePath, readme);
  console.log('→ README.md updated');

  // Snapshot for the preview harness and for eyeballing what the API returned.
  // The 365-day calendar is dropped — it's an implementation detail of the
  // streak maths, and it shifts every day as the rolling window moves, which
  // would make this file differ on every build regardless of real activity.
  writeFileSync(
    join(OUT, 'data.json'),
    `${JSON.stringify({ ...data, stats: { ...data.stats, days: undefined } }, null, 2)}\n`,
  );
}

main().catch((err) => {
  console.error(`\nBuild failed: ${err.message}`);
  process.exit(1);
});
